### ISSUE TITLE
Codificação dos caracteres no csv baixado para importação de ativos está gerando caracteres estranhos

### ISSUE THREAD

**Issue by luisgustavovf** [Menighin/porquinho-digital#1]
Ver imagem em anexo
![image](https://user-images.githubusercontent.com/3406975/97024658-72e11f80-152d-11eb-87f2-ce89f39e21db.png)

**Comment by Menighin** [comment]
Opa @luisgustavovf , tu não importou pro Excel usando um encoding diferente nao?
O Stoincs tá exportando em UTF-8, que é o encoding padrão... Aqui aparentemente está ok... Consegue testar se o seu Excel não está em outro encoding?

![image](https://user-images.githubusercontent.com/2742763/97116837-b7f88380-16de-11eb-8e68-47c162c1a9eb.png)

Abs

**Comment by luisgustavovf** [comment]
De fato, quando carrego os dados para o Excel usando o encoding UTF-8 as informações estão corretas!
