### ISSUE TITLE
Suporte a desdobramentos e grupamentos

### ISSUE THREAD

**Issue by armanhi** [Menighin/porquinho-digital#5]
Olá!

Primeiramente parabéns pelo trabalho. Parece bem bacana e redondinho!

Gostaria de saber se existe o suporte a grupamentos e desdobramentos, pois notei que eles geram discrepâncias em valores consolidados, de PM, etc.

Obrigado

**Comment by felipesdias** [comment]
Boa tarde,

Basicamente fazemos a extração das informações que o CEI disponibiliza, se ele disponibilizar ou der para inferir a informação de desdobramento/agrupamento, imagino que seja possível sim.

Como nenhuma das minhas ações tiveram desdobramento/agrupamento, então não sei dizer se é possível.

**Comment by Menighin** [comment]
Oi @armanhi !
Como o Felipe disse, a integração só pega automaticament o extrato do CEI.
Então, automaticamente os desdobramentos / agrupamentos nao sao feitos.
Porém na tela `Ações -> Extratos` existe uma opção para fazer o split:

![split button](https://user-images.githubusercontent.com/2742763/110389598-822bba00-8043-11eb-89fc-84b2b4d890e5.png)

Basta que você informe o ativo, data do split e proporção e o Stoincs irá atualizar todas as suas negociações do ativo até a data do split para refletir o novo preço negociado, atualizando assim os relatorios, preços médios, etc. Exemplo:

![image](https://user-images.githubusercontent.com/2742763/110389754-bb642a00-8043-11eb-8017-9aa7050a286b.png)

**Comment by Menighin** [comment]
Vou fechar, se tiver mais duvidas fica a vontade pra reabrir!

**Comment by armanhi** [comment]
Desculpem, não vi as notificações.

Ah, legal! Vou testar, muito obrigado.
